import React from 'react';
import { motion } from 'framer-motion';

const AILearningPathCard = ({ learningPaths, isLoading = false }) => {
  if (!learningPaths) {
    return null;
  }

  const cardVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.5 } }
  };

  const itemVariants = {
    hidden: { opacity: 0, x: -10 },
    visible: { opacity: 1, x: 0 }
  };

  return (
    <motion.div
      className="sgr-card sgr-ai-learning-card"
      variants={cardVariants}
      initial="hidden"
      animate="visible"
    >
      <div className="sgr-card-header">
        <h3 className="sgr-card-title">
          <span className="sgr-ai-badge">AI ✨</span>
          PERSONALIZED LEARNING PATHS
        </h3>
        <p className="sgr-card-subtitle">
          {learningPaths.source === 'nvidia-ai' 
            ? 'Generated by NVIDIA AI' 
            : 'Recommended paths to close your skill gaps'}
        </p>
      </div>

      <div className="sgr-learning-paths-container">
        {isLoading ? (
          <div className="sgr-loading-state">
            <div className="sgr-spinner"></div>
            <p>Generating personalized learning paths...</p>
          </div>
        ) : (
          <motion.div
            className="sgr-paths-grid"
            initial="hidden"
            animate="visible"
            variants={{
              visible: {
                transition: {
                  staggerChildren: 0.1
                }
              }
            }}
          >
            {learningPaths.learningPaths && learningPaths.learningPaths.map((path, index) => (
              <motion.div
                key={path.id || index}
                className="sgr-learning-path-item"
                variants={itemVariants}
              >
                <div className="sgr-path-number">{index + 1}</div>
                
                <div className="sgr-path-content">
                  <h4 className="sgr-path-skill">{path.skill}</h4>
                  <p className="sgr-path-description">{path.description}</p>
                  
                  <div className="sgr-path-meta">
                    <div className="sgr-time-badge">
                      <span className="sgr-time-icon">⏱️</span>
                      {path.timeEstimate}
                    </div>
                    {path.source === 'AI Generated' && (
                      <div className="sgr-source-badge">AI Generated</div>
                    )}
                  </div>
                </div>
              </motion.div>
            ))}
          </motion.div>
        )}
      </div>

      <div className="sgr-path-cta">
        <p className="sgr-path-instruction">
          Follow these paths in order to maximize your employability growth by 2030
        </p>
      </div>
    </motion.div>
  );
};

export default AILearningPathCard;
